import type {
  AppSettings,
  ExerciseDefinition,
  ImageCrop,
  WorkoutType,
} from "./models";

export const INFOGRAPHIC_SIZE = { width: 1122, height: 1402 } as const;

// These crop windows use the original 1122 x 1402 reference without
// rewriting or hotlinking it. They intentionally focus on the machine/motion.
export const IMAGE_CROPS: Record<string, ImageCrop> = {
  incline_chest_press: {
    key: "incline_chest_press",
    label: "Incline chest press machine",
    x: 38,
    y: 312,
    width: 250,
    height: 286,
  },
  shoulder_press: {
    key: "shoulder_press",
    label: "Selectorized seated shoulder press machine",
    x: 0,
    y: 0,
    width: 1536,
    height: 1024,
    asset: "workout-shoulder-press.png",
    sourceWidth: 1536,
    sourceHeight: 1024,
  },
  lateral_raise: {
    key: "lateral_raise",
    label: "Cable lateral raise",
    x: 319,
    y: 301,
    width: 239,
    height: 298,
  },
  triceps_pushdown: {
    key: "triceps_pushdown",
    label: "Cable triceps pushdown",
    x: 588,
    y: 306,
    width: 231,
    height: 294,
  },
  overhead_triceps_extension: {
    key: "overhead_triceps_extension",
    label: "Overhead cable triceps extension",
    x: 850,
    y: 306,
    width: 230,
    height: 294,
  },
  lat_pulldown: {
    key: "lat_pulldown",
    label: "Lat pulldown machine",
    x: 36,
    y: 867,
    width: 189,
    height: 272,
  },
  chest_supported_row: {
    key: "chest_supported_row",
    label: "Chest-supported row machine",
    x: 239,
    y: 865,
    width: 205,
    height: 274,
  },
  reverse_pec_deck: {
    key: "reverse_pec_deck",
    label: "Reverse pec deck",
    x: 463,
    y: 865,
    width: 202,
    height: 274,
  },
  preacher_or_cable_curl: {
    key: "preacher_or_cable_curl",
    label: "Biceps curl",
    x: 0,
    y: 0,
    width: 1536,
    height: 1024,
    asset: "workout-low-cable-biceps-curl.png",
    sourceWidth: 1536,
    sourceHeight: 1024,
  },
  hammer_curl: {
    key: "hammer_curl",
    label: "Cable hammer curl",
    x: 909,
    y: 865,
    width: 183,
    height: 274,
  },
  leg_press: {
    key: "leg_press",
    label: "45-degree leg press machine",
    x: 18,
    y: 18,
    width: 493,
    height: 489,
    asset: "workout-legs-abs.png",
    sourceWidth: 1536,
    sourceHeight: 1024,
  },
  low_step_up: {
    key: "low_step_up",
    label: "Supported low step-up",
    x: 12,
    y: 12,
    width: 812,
    height: 906,
    asset: "workout-step-woodchop.png",
    sourceWidth: 1693,
    sourceHeight: 929,
  },
  single_leg_extension: {
    key: "single_leg_extension",
    label: "Selectorized seated single-leg extension machine",
    x: 0,
    y: 0,
    width: 1536,
    height: 1024,
    asset: "workout-single-leg-extension.png",
    sourceWidth: 1536,
    sourceHeight: 1024,
  },
  abdominal_crunch_machine: {
    key: "abdominal_crunch_machine",
    label: "Selectorized seated abdominal crunch machine",
    x: 20,
    y: 20,
    width: 735,
    height: 984,
    asset: "workout-ab-priority.png",
    sourceWidth: 1536,
    sourceHeight: 1024,
  },
  reverse_crunch: {
    key: "reverse_crunch",
    label: "Reverse crunch on a flat bench",
    x: 780,
    y: 20,
    width: 735,
    height: 984,
    asset: "workout-ab-priority.png",
    sourceWidth: 1536,
    sourceHeight: 1024,
  },
};

// These former defaults remain valid in historical set records, but should no
// longer be offered when a new Legs + Abs session is created.
export const RETIRED_EXERCISE_IDS = [
  "cable_crunch",
  "captains_chair_knee_raise",
  "cable_wood_chop",
  "low_step_up",
  "hammer_curl",
  "reverse_crunch",
] as const;

export const DEFAULT_EXERCISES: ExerciseDefinition[] = [
  {
    id: "incline_chest_press",
    workoutType: "push",
    order: 0,
    name: "Incline Chest Press Machine",
    minReps: 8,
    maxReps: 12,
    targetSets: 3,
    restSeconds: 180,
    incrementLb: 5,
    imageKey: "incline_chest_press",
  },
  {
    id: "shoulder_press",
    workoutType: "push",
    order: 1,
    name: "Shoulder Press Machine",
    minReps: 8,
    maxReps: 12,
    targetSets: 3,
    restSeconds: 180,
    incrementLb: 5,
    imageKey: "shoulder_press",
  },
  {
    id: "lateral_raise",
    workoutType: "push",
    order: 2,
    additionalWorkoutOrders: { legs_abs: 3 },
    name: "Machine or Cable Lateral Raise",
    minReps: 12,
    maxReps: 20,
    targetSets: 3,
    restSeconds: 120,
    incrementLb: 5,
    imageKey: "lateral_raise",
  },
  {
    id: "triceps_pushdown",
    workoutType: "push",
    order: 3,
    name: "Triceps Pushdown (Cable)",
    minReps: 10,
    maxReps: 15,
    targetSets: 2,
    restSeconds: 120,
    incrementLb: 5,
    imageKey: "triceps_pushdown",
  },
  {
    id: "overhead_triceps_extension",
    workoutType: "push",
    order: 4,
    name: "Overhead Triceps Extension (Cable)",
    minReps: 10,
    maxReps: 15,
    targetSets: 2,
    restSeconds: 120,
    incrementLb: 5,
    imageKey: "overhead_triceps_extension",
  },
  {
    id: "lat_pulldown",
    workoutType: "pull",
    order: 0,
    name: "Lat Pulldown",
    minReps: 8,
    maxReps: 12,
    targetSets: 3,
    restSeconds: 180,
    incrementLb: 5,
    imageKey: "lat_pulldown",
  },
  {
    id: "chest_supported_row",
    workoutType: "pull",
    order: 1,
    name: "Chest-Supported Row",
    minReps: 8,
    maxReps: 12,
    targetSets: 3,
    restSeconds: 180,
    incrementLb: 5,
    imageKey: "chest_supported_row",
  },
  {
    id: "reverse_pec_deck",
    workoutType: "pull",
    order: 2,
    name: "Reverse Pec Deck",
    minReps: 12,
    maxReps: 20,
    targetSets: 2,
    restSeconds: 120,
    incrementLb: 5,
    imageKey: "reverse_pec_deck",
  },
  {
    id: "preacher_or_cable_curl",
    workoutType: "pull",
    order: 3,
    name: "Biceps Curl",
    minReps: 10,
    maxReps: 15,
    targetSets: 3,
    restSeconds: 120,
    incrementLb: 5,
    imageKey: "preacher_or_cable_curl",
  },
  {
    id: "leg_press",
    workoutType: "legs_abs",
    order: 0,
    name: "45-Degree Leg Press",
    minReps: 8,
    maxReps: 12,
    targetSets: 2,
    restSeconds: 180,
    incrementLb: 10,
    imageKey: "leg_press",
  },
  {
    id: "single_leg_extension",
    workoutType: "legs_abs",
    order: 1,
    name: "Single-Leg Extension Machine (Each Leg)",
    minReps: 10,
    maxReps: 15,
    targetSets: 2,
    restSeconds: 120,
    incrementLb: 5,
    imageKey: "single_leg_extension",
  },
  {
    id: "abdominal_crunch_machine",
    workoutType: "legs_abs",
    order: 2,
    name: "Abdominal Crunch Machine",
    minReps: 8,
    maxReps: 15,
    targetSets: 4,
    restSeconds: 90,
    incrementLb: 5,
    imageKey: "abdominal_crunch_machine",
  },
];

export function exerciseOrderForWorkout(
  exercise: ExerciseDefinition,
  workoutType: WorkoutType,
): number | undefined {
  return exercise.workoutType === workoutType
    ? exercise.order
    : exercise.additionalWorkoutOrders?.[workoutType];
}

export function workoutExercises(
  exercises: ExerciseDefinition[],
  workoutType: WorkoutType,
): ExerciseDefinition[] {
  return exercises
    .filter(
      (exercise) =>
        exerciseOrderForWorkout(exercise, workoutType) !== undefined,
    )
    .sort(
      (a, b) =>
        exerciseOrderForWorkout(a, workoutType)! -
        exerciseOrderForWorkout(b, workoutType)!,
    );
}

export const DEFAULT_SETTINGS: AppSettings = {
  id: "settings",
  weightUnit: "lb",
};
